mvc5/src/Demo/Models/RespondToViewModel.cs
using System.Collections.Generic;
using Newtonsoft.Json.Serialization;

namespace Demo.Models
{
    public class RespondToViewModel
    {
        public IList<string> Items { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int HasNextPage { get; set; }
        public int HasPrevPage { get; set; }
        public int TotalPages { get; set; }
    }
}

mvc5/src/Demo/Controllers/RespondToController.cs
using System.Linq;
using System.Web.Mvc;
using Demo.Models;
using PagedList;
using Ploeh.AutoFixture;

namespace Demo.Controllers
{
    public class RespondToController : Controller
    {
        // GET: RespondTo
        public ActionResult Index(int page = 1, int pageSize = 10)
        {
            var fixture = new Fixture();
            var list = fixture.CreateMany<string>(100);
            var paged = list.ToPagedList(page, pageSize);
            
            
            return View(new RespondToViewModel
            {
                Items = paged.ToList(),
                HasNextPage = paged.HasNextPage ? 1 :0,
                HasPrevPage = paged.HasPreviousPage ? 1 : 0,
                CurrentPage = paged.PageNumber,
                PageSize = paged.PageSize,
                TotalPages = paged.PageCount
            });
        }
    }
}

mvc5/src/Demo/Views/RespondTo/Index.cshtml
@model Demo.Models.RespondToViewModel

@{
    ViewBag.Title = "Respond To";
}

@section scripts
{
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.2/angular.js"></script>
    <script>
        angular.module('demo', [])
            .run(function($http) {
                $http.defaults.headers.common.Accept = 'application/json';
            })
            .controller('DemoController', function($http) {
                var ctrl = this;

                ctrl.currentPage = @Model.CurrentPage;
                ctrl.hasNextPage = @Model.HasNextPage === 1;
                ctrl.hasPrevPage = @Model.HasPrevPage === 1;
                ctrl.totalPages = @Model.TotalPages;

                ctrl.list = [];

                @foreach (var respondToViewModel in Model.Items)
                {
                    @Html.Raw($"ctrl.list.push('{respondToViewModel}');")
                }

                ctrl.nextPage = function() {
                    if(ctrl.hasNextPage)
                        getResultsPage(ctrl.currentPage + 1);
                };

                ctrl.prevPage = function() {
                    if(ctrl.hasPrevPage)
                        getResultsPage(ctrl.currentPage - 1);
                }

                function getResultsPage(pageNumber) {
                    // this is just an example, in reality this stuff should be in a service
                    $http.get('@Url.Action("Index", "RespondTo")?page=' + pageNumber)
                        .then(function (result) {
                            ctrl.list = result.data.Items;
                            ctrl.currentPage = result.data.CurrentPage;
                            ctrl.hasNextPage = result.data.HasNextPage === 1;
                            ctrl.hasPrevPage = result.data.HasPrevPage === 1;
                            ctrl.totalPages = result.data.TotalPages;
                        });
                }

                return ctrl;
            })
    </script>
}

<h2>RespondTo</h2>

<div ng-app="demo">
    <div ng-controller="DemoController as ctrl">
        <table class="table table-bordered table-condensed">
            <thead>
                <tr>
                    <th>
                        Text
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="text in ctrl.list">
                    <td>{{text}}</td>
                </tr>
            </tbody>
        </table>

        <nav>
            <ul class="pagination">
                <li ng-class="{disabled: !ctrl.hasPrevPage}">
                    <a ng-click="ctrl.prevPage()" href="#">
                        <span>&laquo;</span>
                    </a>
                </li>
                <li ng-class="{disabled: !ctrl.hasNextPage}">
                    <a ng-click="ctrl.nextPage()" href="#">
                        <span>&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>

        <span>Page {{ctrl.currentPage}} of {{ctrl.totalPages}}</span>
    </div>
</div>